<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Data center  enterprise computing</name>
   <tag></tag>
   <elementGuidId>a26b76cf-393a-4c75-8535-84932fc91232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ti-breadcrumb-section-3-item-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ti-breadcrumb-section-3-item-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ti-breadcrumb-section-3-item-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf1d64f7-28cc-4f6c-98d4-1063cc79e645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-breadcrumb-section-link</value>
      <webElementGuid>50ec93d9-ec73-4c09-a676-976dbcebbf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ti-breadcrumb-section-3-item-1</value>
      <webElementGuid>4e1ff09d-c531-4d2b-9f1b-466862922acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.ti.com/applications/enterprise-systems/datacenter-enterprise-computing/overview.html</value>
      <webElementGuid>66752e22-2776-4ab7-8a22-f6fb4ebfc156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtitle</name>
      <type>Main</type>
      <value>data_center_&amp;_enterprise_computing</value>
      <webElementGuid>1e99fd93-c91b-4633-a186-a982b73389f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>#ti-breadcrumb-section-3-item-1</value>
      <webElementGuid>10ac205c-581f-4cbf-a524-712bcc6af91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Data center &amp; enterprise computing</value>
      <webElementGuid>9b1d6cfa-615b-4d19-a721-2a49609b339a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ti-breadcrumb-section-3-item-1&quot;)</value>
      <webElementGuid>db9a081f-f818-4b59-a76c-8e96db6ae737</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ti-breadcrumb-section-3-item-1']</value>
      <webElementGuid>a58df654-f46d-4686-9570-20d94343bd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='sectorLevelPage-89b20fdbd1']/main/div/div/nav/div/ti-breadcrumb/ti-breadcrumb-section[4]/div/ti-dropdown-panel/div[2]/ul/li/a</value>
      <webElementGuid>3981f2fd-f29d-4fca-9156-0f41c9ed82e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Data center &amp; enterprise computing')])[2]</value>
      <webElementGuid>0949a2a0-fe01-4ac7-9651-f5106cb4c603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data center &amp; enterprise computing'])[1]/following::a[1]</value>
      <webElementGuid>7ed4c1a1-3f9e-4118-9c86-62f954dcf84f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal electronics'])[1]/following::a[2]</value>
      <webElementGuid>42c01017-4263-428e-83ff-e71752b2b07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise machine'])[1]/preceding::a[1]</value>
      <webElementGuid>f76fb950-20d4-4322-ac42-0be72d83cdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enterprise projectors'])[1]/preceding::a[2]</value>
      <webElementGuid>ae18d059-a265-4550-b5f4-d3e4a0a24aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.ti.com/applications/enterprise-systems/datacenter-enterprise-computing/overview.html')])[2]</value>
      <webElementGuid>bf6d77b9-ca7d-46f2-b255-51928712d8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ti-breadcrumb-section[4]/div/ti-dropdown-panel/div[2]/ul/li/a</value>
      <webElementGuid>5cac9d7b-d7fc-49d1-9714-2e1c3644b52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ti-breadcrumb-section-3-item-1' and @href = 'https://www.ti.com/applications/enterprise-systems/datacenter-enterprise-computing/overview.html' and (text() = 'Data center &amp; enterprise computing' or . = 'Data center &amp; enterprise computing')]</value>
      <webElementGuid>eb018232-7ee9-47c6-a1b0-06f2c667f423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
