<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e6dc6916-6ac4-41d3-a9cd-f88c088f6722</elementGuidId>
    <imagePath></imagePath>
    <name>header_tableOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[2]/article[1]/h2[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>h2:nth-of-type(${header_tableOptions_h2NthOfType})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>h2:nth-child(${header_tableOptions_h2NthChild})</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>