<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4eddc922-ab9f-4a1a-9a5d-acabeef4a9e1</elementGuidId>
    <imagePath></imagePath>
    <name>link_freeUiDesignSoftware</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/header[1]/div[1]/nav[1]/nav[1]/div[1]/ul[1]/li[1]/div[1]/div[1]/ul[1]/div[1]/li[2]/div[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="item_68994bb37fcc2"] a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Free ui design software')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Free ui design software\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>79add74e-7497-4eea-88f4-e33d360bc73f</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Free ui design software</value>
        <webElementGuid>79add74e-7497-4eea-88f4-e33d360bc73f</webElementGuid>
    </webElementProperties>
</WebElementEntity>