<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a47f27d8-dfd3-4f31-9f95-362ce41ef52e</elementGuidId>
    <imagePath></imagePath>
    <name>item_selectRows</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[1]/ul[1]/li[3]/ul[1]/li[3]/ul[1]/li[6]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.content &gt; li:nth-of-type(6)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.expanded &gt; .list-child &gt; li:nth-child(6)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>