<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d0dafa17-0177-4725-8358-154577c91534</elementGuidId>
    <imagePath></imagePath>
    <name>i_topicStatus</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[1]/i[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${i_topicStatus_id}"] .ico-small</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#topic-${i_topicStatus_topic} i &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>