<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3d342a01-60a4-4c52-8577-8349cad976ef</elementGuidId>
    <imagePath></imagePath>
    <name>input_search</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[2]/form[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="search"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'search') and equals(@type,'text')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>input[placeholder=\"What are you looking for\\?\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>search</value>
        <webElementGuid>febbc47d-899c-4605-b671-096658e92b15</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>text</value>
        <webElementGuid>febbc47d-899c-4605-b671-096658e92b15</webElementGuid>
    </webElementProperties>
</WebElementEntity>